name: Daily Index Change Check

on:
  schedule:
    # Run at 6:00 PM UTC (after market close in the US)
    - cron: '0 18 * * 1-5'
  workflow_dispatch:  # Allow manual triggering for testing

jobs:
  check-index-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Verify installations
          pip list | grep pandas
          pip list | grep openpyxl
      
      - name: Run change detection script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: python scripts/check_changes.py
      
      - name: Archive raw ETF files
        uses: actions/upload-artifact@v3
        with:
          name: raw-etf-files
          path: data/raw/
          retention-days: 7  # Keep for 7 days
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/*.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update index data [skip ci]"
        continue-on-error: true
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true