name: Daily QQQ Change Check

on:
  schedule:
    # Run at 6:00 PM UTC (after US market close) - weekdays only
    - cron: '0 18 * * 1-5'
  workflow_dispatch:  # Allow manual triggering for testing and development

jobs:
  check-qqq-changes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated from v3 to v4
      
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated from v4 to v5
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Verify critical package installations for QQQ processing
          echo "Verifying key packages..."
          pip list | grep pandas && echo "✓ pandas installed" || echo "✗ pandas missing"
          pip list | grep openpyxl && echo "✓ openpyxl installed" || echo "✗ openpyxl missing"
          pip list | grep numpy && echo "✓ numpy installed" || echo "✗ numpy missing"
          pip list | grep requests && echo "✓ requests installed" || echo "✗ requests missing"
      
      - name: Run QQQ change detection
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: |
          echo "🚀 Starting QQQ (Nasdaq-100) change detection..."
          echo "Timestamp: $(date -u)"
          python scripts/check_changes.py
          echo "✅ QQQ change detection completed"
      
      - name: Archive QQQ data and analysis
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if previous steps failed
        with:
          name: qqq-analysis-${{ github.run_id }}
          path: |
            data/raw/
            data/cache/
            data/qqq_current.json
          retention-days: 14  # Keep for 2 weeks for better troubleshooting
      
      - name: Commit QQQ data updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "QQQ Monitor Bot"
          # Only add QQQ-related data files
          git add data/qqq_current.json || true
          git add data/shares_outstanding.json || true
          # Check if there are changes to commit
          if git diff --quiet && git diff --staged --quiet; then
            echo "ℹ️ No QQQ data changes to commit"
          else
            echo "📝 Committing QQQ data updates..."
            git commit -m "Update QQQ data [skip ci] - $(date -u +'%Y-%m-%d %H:%M UTC')"
            echo "✅ Changes committed successfully"
          fi
        continue-on-error: true
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        continue-on-error: true